### ISSUE TITLE
[NEW REQUEST] kavita

### ISSUE THREAD

**Issue by faritvidal** [kubesail/apps#86] opened 2022-09-15 21:53 UTC
**Website**: https://demo.kavitareader.com/login
**GitHub**: https://github.com/Kareadita/Kavita
**Docker Image**: https://hub.docker.com/r/kizaing/kavita
**Has arm64 image**: YES

**Comment by DrMxrcy** [comment] 2022-09-16 02:19
Duplicate of #68. I will work on this tomorrow!

**Closed by DrMxrcy** 2022-09-16 02:19 UTC

**Comment by DrMxrcy** [comment] 2022-09-16 12:25
@faritvidal Added :) https://kubesail.com/template/jphj/Kavita
